# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    # - id: check-json
    - id: check-toml
    - id: check-xml
    - id: debug-statements
    # - id: detect-aws-credentials
    #     args: [--allow-missing-credentials]
    - id: detect-private-key
    # - id: no-commit-to-branch   # to protect specific branches from direct checkins.
    #     args: [--branch, master]
    # - id: pretty-format-json
    #     args: [--autofix]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: ["--profile", "black"]

- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    language_version: python3

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.5.1
#   hooks:
#     - id: mypy
#       args: [--strict, --ignore-missing-imports]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    # max-line-length setting is the same as black
    # commit cannot be done when cyclomatic complexity is more than 10.
    args: [--max-line-length, "88", --ignore=E402, --max-complexity, "10", --max-expression-complexity=7, --max-cognitive-complexity=7]
    additional_dependencies: [flake8-bugbear, flake8-builtins, flake8-eradicate, pep8-naming, flake8-expression-complexity, flake8-cognitive-complexity]

# - repo: https://github.com/markdownlint/markdownlint
#   rev: v0.12.0
#   hooks:
#     - id: markdownlint
#       # ignore line length of makrdownlint
#       args: [-r, ~MD013]
